#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}


use AwsUpload\AwsUpload;

$aws = new AwsUpload('1.0.5');
$aws->run();
